name: Publish docs
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'fair_test/**'
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/deploy-docs.yml'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install ".[doc]"

      - name: Deploy mkdocs on GitHub Pages
        run: |
          git pull
          mkdocs gh-deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
