name: Publish to PyPI
# Publish to PyPI when new release on GitHub, if tests pass
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  tests:
    uses: MaastrichtU-IDS/fair-test/.github/workflows/test.yml@main
    secrets: inherit

  publish:
    needs: [ tests ]
    runs-on: ubuntu-latest
    name: Publish to PyPI

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.7"

    - uses: actions/cache@v3
      id: cache
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-publish

    - name: Install build dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: pip install build

    - name: Build distribution
      run: python -m build

    - name: Publish
      uses: pypa/gh-action-pypi-publish@v1.5.1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
